name: CI - 🧪
on:
  push:
    branches:
      - main
      
jobs:
  javascript:
    name: api test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd javascript
          npm ci
      - name: Test with mocha
        run: npm test
       
