name: CI - 🧪
on:
  push:
    branches:
      - 'v**'
jobs:
  postman:
    name: api test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Preparing test
        run: |
          npm install mocha --save-dev
          npm install jest --save-dev
          npm install supertest --save-dev
          npm ci
      - name: Test with newman
        run: |
          cd postman
          newman run APITest.postman_collection.json
       
